apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: opj4owcwi-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:8841f98bfce0c9947eeaa9d72381081a748ba741@sha256:2098f5c12128a9abcceb99ea211493ac7b78f8cf55ab3b005ca2782898b3c8f8
          name: container-image
